### ISSUE TITLE
App crashing when a user clicks on a child

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-giz-malawi#204]
**Reproduction steps**

- Create a user
- Register BCG 
- Turn off BCG Scar reminder

**Logs**
```
02-14 12:24:36.887 21904 21904 D AndroidRuntime: Shutting down VM
02-14 12:24:36.887 21904 21904 E AndroidRuntime: FATAL EXCEPTION: main
02-14 12:24:36.887 21904 21904 E AndroidRuntime: Process: org.smartregister.giz, PID: 21904
02-14 12:24:36.887 21904 21904 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.smartregister.child.view.LocationActionView.getSelectedItem()' on a null object reference
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.toolbar.LocationSwitcherToolbar.getCurrentLocation(LocationSwitcherToolbar.java:52)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.activity.BaseChildImmunizationActivity.createDummyVaccine(BaseChildImmunizationActivity.java:854)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.activity.BaseChildImmunizationActivity.updateVaccinationViews(BaseChildImmunizationActivity.java:791)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.activity.BaseChildImmunizationActivity.access$2100(BaseChildImmunizationActivity.java:125)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.activity.BaseChildImmunizationActivity$UpdateViewTask.onPostExecute(BaseChildImmunizationActivity.java:1903)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at org.smartregister.child.activity.BaseChildImmunizationActivity$UpdateViewTask.onPostExecute(BaseChildImmunizationActivity.java:1804)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7179)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-14 12:24:36.887 21904 21904 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
02-14 12:24:36.960  3165  3165 D CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1482000  uid : 1000  pid : 3165  tag : AMS_RESUME_TAIL@CPU_MIN@22
02-14 12:24:37.000  3165 17599 D ConnectivityService: filterNetworkStateForUid() uid: 10616, pid: 21904
02-14 12:24:37.000  3165 17599 D ConnectivityService: filterNetworkStateForUid() uid: 10616, pid: 21904, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
02-14 12:24:37.002 21904 21936 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-14 12:24:37.002 21904 21936 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-14 12:24:37.002  3165 13208 D Debug   : !@DumpState : SHIP
02-14 12:24:37.002  3165 13208 D Debug   : !@DumpState : debug level:0x4f4c
02-14 12:24:37.002  3165 13208 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
02-14 12:24:37.003  3165 13208 W ActivityManager: crash : org.smartregister.giz,0
02-14 12:24:37.005  2893  2990 D EnterpriseController: netId is 0
02-14 12:24:37.005  3165 13208 W ActivityManager:   Force finishing activity org.smartregister.giz/.activity.ChildImmunizationActivity
```

**Comment by Mstjamush** [comment]
This issue has regressed

**Comment by Mstjamush** [comment]
Fixed and tested
